stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - npm install
    - bower install
    - grunt test
  except:
    - production

deploy:
  stage: deploy
  script:
    - npm install
    - bower install
    - grunt build
    - ./deploy.sh
  only:
    - production
