stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  script:
    - npm install
    - npm run build
    - ./deploy.sh
  only:
    - master
