stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - bower install
    - grunt test

deploy:
  stage: deploy
  script:
    - npm install
    - bower install
    - grunt build
    - ./deploy.sh
  only:
    - master
